### ISSUE TITLE
Should compare between configuration files and what exists

### ISSUE THREAD

**Issue by timgent** [UKHomeOffice/vaultconf#1]
Currently:
- if a resource is removed from config files it won't be removed from vault when the tool is run
- if an already existing user is updated it will also generate a new password for them

Instead we should have:
- Comparison of existing entities in vault and entities in the config is made, and reconciled
- If a user already exists instead of replacing them it should just update their policies but leave them with the same password

**Comment by vaijab** [comment]
Agree.

**Comment by timgent** [comment]
FYI... can't list users in Vault so hard to reconcile them:
https://github.com/hashicorp/vault/issues/111
for the moment will look at reconciling by relying on reading user details from kubernetes secrets (will work for application vault logins anyway...)

**Comment by timgent** [comment]
This has been implemented now. It uses details of vault user secrets in kubernetes to reconcile users
