### ISSUE TITLE
Missing a travis ci config

### ISSUE THREAD

**Issue by PurpleBooth** [UKHomeOffice/vaultconf#14]
Make life easier for people submitting code to your repository. Make sure that you double check that their code works the best you can (even if that's just running a build of the package) in travis. This way potential contributors can fix bugs before you even need to look at their request. https://gist.github.com/PurpleBooth/6f1ba788bf70fb501439

**Comment by PurpleBooth** [comment]
Also there are already lots of lovely tests in this repo. It'd make sense to use them :)

**Comment by timgent** [comment]
All done :) The cucumber features require a vault binary so it can start a vault test server so not running those at the minute. At some point though could dockerise those tests
