### ISSUE TITLE
Documentation: Use-cases

### ISSUE THREAD

**Issue by connec** [UKHomeOffice/vaultconf#17]
I would be interested to see a couple of lines in the README with what use-cases this project was designed to solve.

Context: I came across it whilst looking for a way to import/export secrets to/from Vault. It looks like it could be used for that purpose, however the Kubernetes integration made me wonder what it was initially for.

**Comment by timgent** [comment]
I've added a note to the readme with a link to a blog post on the topic:
http://timturnstechie.blogspot.co.uk/2015/10/vaultconf-managing-vault-logins-for.html

Note this project hasn't been under active development for a while but may still be a helpful starting point. The features directory has some useful tests that may help you see what it's able to do, especially as the features currently only cover pure vault functionality and not kubernetes functionality.
