### ISSUE TITLE
secrets management

### ISSUE THREAD

**Issue by gambol99** [UKHomeOffice/vaultconf#9]
Could we have the secrets, aws policys etc manageable from the same tool

**Comment by vaijab** [comment]
One tool to rule them all? Not sure that works in practice well.

**Comment by timgent** [comment]
I get wanting vault AWS policies managed in the same tool, think that makes sense, given we are managing vault policies with it. Not sure what you mean by secrets though? Surely we don't want our secrets in github? The point of vault is to securely house our secrets.

**Comment by gambol99** [comment]
So by secrets, example ... i mount aws backend and i push 12 aws iam policies giving access to this, (ses, s3, etc etc) that and the other ... then some bastard comes along and destroys my vault and i have to remember this policies and import them back into ... but if i have them in a repo somewhere ... vaultconf secrets -c filename

**Comment by timgent** [comment]
Yep still agree for aws iam policies!

By secrets I thought you meant you wanted stuff like credentials in github
